### PR TITLE
Polygon: fixing Voronoi basic tutorial.

### PR DESCRIPTION
**Pull request by rydotyosh**
The example seems to be broken due to the interface change.

### CODE REVIEW

**Comment by asydorchuk** [comment]
Hi @rydotyosh, thank you for the fix. Merged.

**Comment by rydotyosh** [comment]
How about "doc/voronoi_basic_tutorial.htm"?
Are they generated automatically?

**Comment by asydorchuk** [comment]
@rydotyosh they are not. If you send a pull request that would be great!

**Comment by rydotyosh** [comment]
Thank you. I will try.

**Pull request merged**
